### ISSUE TITLE
Shopify API 2022-07 is no longer supported

### ISSUE THREAD

**Issue by bobbrodie** [singer-io/tap-shopify#174]
This tap currently uses the 2022-07 API as defined in `tap_shopify/__init__.py`:

https://github.com/singer-io/tap-shopify/blob/edbe7a3b950f063eb7d88cffe48f4247db3e4cae/tap_shopify/__init__.py#L28

This is throwing warnings in the Shopify admin and will need to be updated. I'm not sure what policy is for Singer, but the versions of the Shopify API active as of writing this are:

- 2023-07
- 2023-04
- 2023-01
- 2022-10

**Comment by rubenhelsloot** [comment]
My Stitch pipelines are now throwing errors, so this is actually broken now. Any indication of a fix?

**Comment by sameeranand1** [comment]
> My Stitch pipelines are now throwing errors, so this is actually broken now. Any indication of a fix?

I'm having the same problem. I've emailed Stitch support but haven't heard back yet.

**Comment by thieenq** [comment]
we had the same problem, what worked for us is creating a new custom app on Shopify (pick the latest API version, as of now it's `2023-07`, re-create the same connections on Stitch and it should work fine.

although the existing and new connections will use the same API version (i checked the log), somehow the new one works.

**Comment by sameeranand1** [comment]
Stitch fixed the problem yesterday.
