### ISSUE TITLE
Syncing always "Skipping stream"

### ISSUE THREAD

**Issue by tomdean** [singer-io/tap-shopify#40]
I'm unable to get tap-shopify to run a sync - it just outputs "Skipping stream" for everything. 

```
tap-shopify -c config.json -d > catalog.json
tap-shopify -c config.json --catalog catalog.json

INFO Skipping stream: orders
INFO Skipping stream: customers
INFO Skipping stream: custom_collections
INFO Skipping stream: abandoned_checkouts
INFO Skipping stream: products
INFO Skipping stream: transactions
INFO Skipping stream: metafields
INFO Skipping stream: order_refunds
INFO Skipping stream: collects
```

There's no explanation in either tap-shopify or singer what this means or why it's happening. Followed the instructions in the README but it looks like something important is missing.

**Comment by tomdean** [comment]
Found the issue - a ```"selected": true``` has to be added to the metata.metadata in the catalog JSON for each stream to enable. Very confusing, the README should be updated to communicate this otherwise anyone trying this out for the 1st time is going to have the same issue.

**Comment by johncarlov06** [comment]
> Found the issue - a `"selected": true` has to be added to the metata.metadata in the catalog JSON for each stream to enable. Very confusing, the README should be updated to communicate this otherwise anyone trying this out for the 1st time is going to have the same issue.

How to do this? Thanks!

**Comment by dougscc** [comment]
https://github.com/singer-io/getting-started/blob/master/docs/SYNC_MODE.md has a sort-of-okay explanation of this.

**Comment by manavkohli** [comment]
@johncarlov06 not sure if you're still facing this, but otherwise hope this is helpful for anyone else:
1. Run the tap in discovery mode and write the catalog out:
```bash
<tap> -c config.json --discover > catalog.json
```
2. Search for the occurrence of metadata fields in the resulting json. There should be properties such as `table-key-properties` and `forced-replication-method` at the same level. There, add the `"selected": true` property

**Comment by ohld** [comment]
Great example of open-source business anti-pattern: yes, you have your code on Github, but you don't have proper Readme to sell your paid services.

**Comment by Guipetris** [comment]
I guess this only work seamlessly with Meltano, where in their yaml configurations you suppose to select the tables/streams that you want to sync - avoiding this situation.

Pretty bad pattern - but just so you know
